name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "hello"
database_id = "ec1a43bf-ff02-42ad-b2df-7e93d8bdc0e4"
